### ISSUE TITLE
ADMIN PAGE - Logik

### ISSUE THREAD

**Issue by Emilaberg** [Emilaberg/ValhallaVaultCyberAwareness#49]
DESIGNEN E GJORD HÄR ÄR LOGIKEN FÖR ADMIN SIDAN
- [x] hantera questions
- [x] hantera categories
- [x] hantera segments /segments kan ju implemteras med när man skapar en category
- [x] hantera subcategories

**Comment by Gustav-Frising** [comment]
edit & delete has almost been fully handeled

**Comment by Gustav-Frising** [comment]
Edit delete and add has been fully implemented and tested

//TODO: User view page showing all users and some statistics like average score or progress
